from rest_framework import serializers
from .models import Certificate, TransactionLog


class CertificateSerializer(serializers.ModelSerializer):
    class Meta:
        model  = Certificate
        fields = [
            'certificate_id',
            'student_name',
            'course_name',
            'issue_date',
            'certificate_hash',
            'pdf_file',
            'issuer',
            'created_at'
        ]
        read_only_fields = [
            'certificate_id',
            'certificate_hash',
            'created_at'
        ]


class CertificateIssueSerializer(serializers.ModelSerializer):
    """
    Used specifically for issuing — only accepts
    the input fields, hash is generated by the system.
    """
    class Meta:
        model  = Certificate
        fields = ['student_name', 'course_name', 'issue_date', 'pdf_file']


class VerifyResponseSerializer(serializers.Serializer):
    valid            = serializers.BooleanField()
    certificate_id   = serializers.UUIDField(required=False)
    student_name     = serializers.CharField(required=False)
    course_name      = serializers.CharField(required=False)
    issue_date       = serializers.DateField(required=False)
    certificate_hash = serializers.CharField(required=False)
    message          = serializers.CharField()


class TransactionLogSerializer(serializers.ModelSerializer):
    class Meta:
        model  = TransactionLog
        fields = ['id', 'certificate_hash', 'tx_hash', 'blockchain', 'timestamp']