# Generated by Django 6.0.7 on 2026-07-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
